name: Ingesta Diaria Zara
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Esto asegura permiso de escritura
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Llave de acceso

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install requests

      - name: Ejecutar Ingesta
        run: python ingesta.py

      - name: Guardar y subir cambios
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add catalog.json
          # Si no hay cambios, no fallará
          git commit -m "Update catálogo" || echo "No hay cambios"
          git push origin main
